// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package ent

import (
	"customer/ent/customer"
)

type Jwt struct {
	Token     string `json:"token"`
	TokenType string `json:"tokenType"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RegisterInput struct {
	Name             string         `json:"name"`
	PhoneNumber      string         `json:"phoneNumber"`
	Email            string         `json:"email"`
	LicenseID        string         `json:"licenseID"`
	Address          string         `json:"address"`
	MembershipNumber *int           `json:"membershipNumber,omitempty"`
	Password         string         `json:"password"`
	Role             *customer.Role `json:"role,omitempty"`
}
