version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: huongbui
      POSTGRES_PASSWORD: huongbui
      POSTGRES_DB: booking_system
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:

