package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"customer/ent"
	"customer/ent/customer"
	graphql1 "customer/graphql"
	"customer/internal/utils"
	customer2 "customer/proto/customer"
	"customer/proto/flight"
	"customer/service"
	"fmt"
	"strconv"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input ent.RegisterInput) (*ent.Jwt, error) {
	cus, err := customer2.Register(&input)
	if err != nil {
		return nil, err
	}
	token, _ := service.JwtGenerate(int(cus.Id), cus.Role)

	return &ent.Jwt{
		Token:     token,
		TokenType: "Bearer",
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input ent.LoginInput) (*ent.Jwt, error) {
	cus, err := customer2.Login(&input)
	if err != nil {
		return nil, err
	}
	token, _ := service.JwtGenerate(int(cus.GetId()), cus.GetRole())
	return &ent.Jwt{
		Token:     token,
		TokenType: "Bearer",
	}, nil
}

// Update is the resolver for the Update field.
func (r *mutationResolver) Update(ctx context.Context, id string, input ent.UpdateCustomerInput) (*ent.Customer, error) {
	idInt, err := strconv.Atoi(id)
	payload := ctx.Value("auth").(*service.JwtCustomClaim)
	if payload.ID != idInt {
		return nil, utils.WrapGQLUnauthorizedError(ctx)
	}
	if err != nil {
		return nil, err
	}
	cus, err := customer2.Update(&input, idInt)
	return customer2.FromProtoCustomer(cus)
}

// ChangePassword is the resolver for the ChangePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, id string, input ent.ChangePasswordInput) (string, error) {
	idInt, err := strconv.Atoi(id)
	if err != nil {
		return "", err
	}
	return customer2.ChangePassword(&input, idInt)
}

// UpdateRole is the resolver for the UpdateRole field.
func (r *mutationResolver) UpdateRole(ctx context.Context, id string, input customer.Role) (*ent.Customer, error) {
	idInt, err := strconv.Atoi(id)
	if err != nil {
		return nil, err
	}
	cus, err := customer2.UpdateRole(input, idInt)
	return customer2.FromProtoCustomer(cus)
}

// CreateFlight is the resolver for the CreateFlight field.
func (r *mutationResolver) CreateFlight(ctx context.Context, input ent.CreateFlightInput) (*ent.Flight, error) {
	fli, err := flight.CreateFlight(&input)
	if err != nil {
		return nil, err
	}
	return flight.FromProtoFlight(fli)
}

// UpdateFlight is the resolver for the UpdateFlight field.
func (r *mutationResolver) UpdateFlight(ctx context.Context, id string, input ent.UpdateFlightInput) (*ent.Flight, error) {
	numId, err := utils.ConvertStringToInt(id)
	if err != nil {
		return nil, err
	}
	fli, err := flight.UpdateFlight(&input, *numId)
	if err != nil {
		return nil, err
	}
	return flight.FromProtoFlight(fli)
}

// Customers is the resolver for the customers field.
func (r *queryResolver) Customers(ctx context.Context) ([]*ent.Customer, error) {
	panic(fmt.Errorf("not implemented: Customers - customers"))
}

// SearchFlight is the resolver for the SearchFlight field.
func (r *queryResolver) SearchFlight(ctx context.Context, input ent.SearchFlightInput) (*ent.SearchFlightResponse, error) {
	results, err := flight.SearchFlights(&input)
	if err != nil {
		return nil, err
	}

	return flight.ConvertListProtoToFlights(results)
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
