// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FlightsColumns holds the columns for the "flights" table.
	FlightsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "from", Type: field.TypeString},
		{Name: "to", Type: field.TypeString},
		{Name: "depart_date", Type: field.TypeTime},
		{Name: "depart_time", Type: field.TypeTime},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"ON_TIME", "DELAYED", "CANCELLED", "SCHEDULED"}, Default: "SCHEDULED"},
		{Name: "available_slots", Type: field.TypeInt},
		{Name: "return_date", Type: field.TypeTime, Nullable: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"ONE_WAY", "RETURN_TICKET"}},
		{Name: "flight_plane", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// FlightsTable holds the schema information for the "flights" table.
	FlightsTable = &schema.Table{
		Name:       "flights",
		Columns:    FlightsColumns,
		PrimaryKey: []*schema.Column{FlightsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FlightsTable,
	}
)

func init() {
}
