// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"flight-service/ent/flight"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FlightCreate is the builder for creating a Flight entity.
type FlightCreate struct {
	config
	mutation *FlightMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (fc *FlightCreate) SetName(s string) *FlightCreate {
	fc.mutation.SetName(s)
	return fc
}

// SetFrom sets the "from" field.
func (fc *FlightCreate) SetFrom(s string) *FlightCreate {
	fc.mutation.SetFrom(s)
	return fc
}

// SetTo sets the "to" field.
func (fc *FlightCreate) SetTo(s string) *FlightCreate {
	fc.mutation.SetTo(s)
	return fc
}

// SetDepartDate sets the "depart_date" field.
func (fc *FlightCreate) SetDepartDate(t time.Time) *FlightCreate {
	fc.mutation.SetDepartDate(t)
	return fc
}

// SetDepartTime sets the "depart_time" field.
func (fc *FlightCreate) SetDepartTime(t time.Time) *FlightCreate {
	fc.mutation.SetDepartTime(t)
	return fc
}

// SetStatus sets the "status" field.
func (fc *FlightCreate) SetStatus(f flight.Status) *FlightCreate {
	fc.mutation.SetStatus(f)
	return fc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (fc *FlightCreate) SetNillableStatus(f *flight.Status) *FlightCreate {
	if f != nil {
		fc.SetStatus(*f)
	}
	return fc
}

// SetAvailableSlots sets the "available_slots" field.
func (fc *FlightCreate) SetAvailableSlots(i int) *FlightCreate {
	fc.mutation.SetAvailableSlots(i)
	return fc
}

// SetReturnDate sets the "return_date" field.
func (fc *FlightCreate) SetReturnDate(t time.Time) *FlightCreate {
	fc.mutation.SetReturnDate(t)
	return fc
}

// SetNillableReturnDate sets the "return_date" field if the given value is not nil.
func (fc *FlightCreate) SetNillableReturnDate(t *time.Time) *FlightCreate {
	if t != nil {
		fc.SetReturnDate(*t)
	}
	return fc
}

// SetType sets the "type" field.
func (fc *FlightCreate) SetType(f flight.Type) *FlightCreate {
	fc.mutation.SetType(f)
	return fc
}

// SetFlightPlane sets the "flight_plane" field.
func (fc *FlightCreate) SetFlightPlane(s string) *FlightCreate {
	fc.mutation.SetFlightPlane(s)
	return fc
}

// SetCreatedAt sets the "created_at" field.
func (fc *FlightCreate) SetCreatedAt(t time.Time) *FlightCreate {
	fc.mutation.SetCreatedAt(t)
	return fc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fc *FlightCreate) SetNillableCreatedAt(t *time.Time) *FlightCreate {
	if t != nil {
		fc.SetCreatedAt(*t)
	}
	return fc
}

// SetUpdatedAt sets the "updated_at" field.
func (fc *FlightCreate) SetUpdatedAt(t time.Time) *FlightCreate {
	fc.mutation.SetUpdatedAt(t)
	return fc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (fc *FlightCreate) SetNillableUpdatedAt(t *time.Time) *FlightCreate {
	if t != nil {
		fc.SetUpdatedAt(*t)
	}
	return fc
}

// Mutation returns the FlightMutation object of the builder.
func (fc *FlightCreate) Mutation() *FlightMutation {
	return fc.mutation
}

// Save creates the Flight in the database.
func (fc *FlightCreate) Save(ctx context.Context) (*Flight, error) {
	fc.defaults()
	return withHooks(ctx, fc.sqlSave, fc.mutation, fc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (fc *FlightCreate) SaveX(ctx context.Context) *Flight {
	v, err := fc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fc *FlightCreate) Exec(ctx context.Context) error {
	_, err := fc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fc *FlightCreate) ExecX(ctx context.Context) {
	if err := fc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fc *FlightCreate) defaults() {
	if _, ok := fc.mutation.Status(); !ok {
		v := flight.DefaultStatus
		fc.mutation.SetStatus(v)
	}
	if _, ok := fc.mutation.CreatedAt(); !ok {
		v := flight.DefaultCreatedAt
		fc.mutation.SetCreatedAt(v)
	}
	if _, ok := fc.mutation.UpdatedAt(); !ok {
		v := flight.DefaultUpdatedAt
		fc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fc *FlightCreate) check() error {
	if _, ok := fc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Flight.name"`)}
	}
	if _, ok := fc.mutation.From(); !ok {
		return &ValidationError{Name: "from", err: errors.New(`ent: missing required field "Flight.from"`)}
	}
	if _, ok := fc.mutation.To(); !ok {
		return &ValidationError{Name: "to", err: errors.New(`ent: missing required field "Flight.to"`)}
	}
	if _, ok := fc.mutation.DepartDate(); !ok {
		return &ValidationError{Name: "depart_date", err: errors.New(`ent: missing required field "Flight.depart_date"`)}
	}
	if _, ok := fc.mutation.DepartTime(); !ok {
		return &ValidationError{Name: "depart_time", err: errors.New(`ent: missing required field "Flight.depart_time"`)}
	}
	if _, ok := fc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Flight.status"`)}
	}
	if v, ok := fc.mutation.Status(); ok {
		if err := flight.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Flight.status": %w`, err)}
		}
	}
	if _, ok := fc.mutation.AvailableSlots(); !ok {
		return &ValidationError{Name: "available_slots", err: errors.New(`ent: missing required field "Flight.available_slots"`)}
	}
	if v, ok := fc.mutation.AvailableSlots(); ok {
		if err := flight.AvailableSlotsValidator(v); err != nil {
			return &ValidationError{Name: "available_slots", err: fmt.Errorf(`ent: validator failed for field "Flight.available_slots": %w`, err)}
		}
	}
	if _, ok := fc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Flight.type"`)}
	}
	if v, ok := fc.mutation.GetType(); ok {
		if err := flight.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Flight.type": %w`, err)}
		}
	}
	if _, ok := fc.mutation.FlightPlane(); !ok {
		return &ValidationError{Name: "flight_plane", err: errors.New(`ent: missing required field "Flight.flight_plane"`)}
	}
	if _, ok := fc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Flight.created_at"`)}
	}
	if _, ok := fc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Flight.updated_at"`)}
	}
	return nil
}

func (fc *FlightCreate) sqlSave(ctx context.Context) (*Flight, error) {
	if err := fc.check(); err != nil {
		return nil, err
	}
	_node, _spec := fc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	fc.mutation.id = &_node.ID
	fc.mutation.done = true
	return _node, nil
}

func (fc *FlightCreate) createSpec() (*Flight, *sqlgraph.CreateSpec) {
	var (
		_node = &Flight{config: fc.config}
		_spec = sqlgraph.NewCreateSpec(flight.Table, sqlgraph.NewFieldSpec(flight.FieldID, field.TypeInt))
	)
	if value, ok := fc.mutation.Name(); ok {
		_spec.SetField(flight.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := fc.mutation.From(); ok {
		_spec.SetField(flight.FieldFrom, field.TypeString, value)
		_node.From = value
	}
	if value, ok := fc.mutation.To(); ok {
		_spec.SetField(flight.FieldTo, field.TypeString, value)
		_node.To = value
	}
	if value, ok := fc.mutation.DepartDate(); ok {
		_spec.SetField(flight.FieldDepartDate, field.TypeTime, value)
		_node.DepartDate = value
	}
	if value, ok := fc.mutation.DepartTime(); ok {
		_spec.SetField(flight.FieldDepartTime, field.TypeTime, value)
		_node.DepartTime = value
	}
	if value, ok := fc.mutation.Status(); ok {
		_spec.SetField(flight.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := fc.mutation.AvailableSlots(); ok {
		_spec.SetField(flight.FieldAvailableSlots, field.TypeInt, value)
		_node.AvailableSlots = value
	}
	if value, ok := fc.mutation.ReturnDate(); ok {
		_spec.SetField(flight.FieldReturnDate, field.TypeTime, value)
		_node.ReturnDate = &value
	}
	if value, ok := fc.mutation.GetType(); ok {
		_spec.SetField(flight.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := fc.mutation.FlightPlane(); ok {
		_spec.SetField(flight.FieldFlightPlane, field.TypeString, value)
		_node.FlightPlane = value
	}
	if value, ok := fc.mutation.CreatedAt(); ok {
		_spec.SetField(flight.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := fc.mutation.UpdatedAt(); ok {
		_spec.SetField(flight.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// FlightCreateBulk is the builder for creating many Flight entities in bulk.
type FlightCreateBulk struct {
	config
	builders []*FlightCreate
}

// Save creates the Flight entities in the database.
func (fcb *FlightCreateBulk) Save(ctx context.Context) ([]*Flight, error) {
	specs := make([]*sqlgraph.CreateSpec, len(fcb.builders))
	nodes := make([]*Flight, len(fcb.builders))
	mutators := make([]Mutator, len(fcb.builders))
	for i := range fcb.builders {
		func(i int, root context.Context) {
			builder := fcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FlightMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fcb *FlightCreateBulk) SaveX(ctx context.Context) []*Flight {
	v, err := fcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fcb *FlightCreateBulk) Exec(ctx context.Context) error {
	_, err := fcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fcb *FlightCreateBulk) ExecX(ctx context.Context) {
	if err := fcb.Exec(ctx); err != nil {
		panic(err)
	}
}
