// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"flight-service/ent/flight"
	"flight-service/ent/predicate"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// FlightUpdate is the builder for updating Flight entities.
type FlightUpdate struct {
	config
	hooks    []Hook
	mutation *FlightMutation
}

// Where appends a list predicates to the FlightUpdate builder.
func (fu *FlightUpdate) Where(ps ...predicate.Flight) *FlightUpdate {
	fu.mutation.Where(ps...)
	return fu
}

// SetName sets the "name" field.
func (fu *FlightUpdate) SetName(s string) *FlightUpdate {
	fu.mutation.SetName(s)
	return fu
}

// SetFrom sets the "from" field.
func (fu *FlightUpdate) SetFrom(s string) *FlightUpdate {
	fu.mutation.SetFrom(s)
	return fu
}

// SetTo sets the "to" field.
func (fu *FlightUpdate) SetTo(s string) *FlightUpdate {
	fu.mutation.SetTo(s)
	return fu
}

// SetDepartDate sets the "depart_date" field.
func (fu *FlightUpdate) SetDepartDate(t time.Time) *FlightUpdate {
	fu.mutation.SetDepartDate(t)
	return fu
}

// SetDepartTime sets the "depart_time" field.
func (fu *FlightUpdate) SetDepartTime(t time.Time) *FlightUpdate {
	fu.mutation.SetDepartTime(t)
	return fu
}

// SetReturnDate sets the "return_date" field.
func (fu *FlightUpdate) SetReturnDate(t time.Time) *FlightUpdate {
	fu.mutation.SetReturnDate(t)
	return fu
}

// SetStatus sets the "status" field.
func (fu *FlightUpdate) SetStatus(s string) *FlightUpdate {
	fu.mutation.SetStatus(s)
	return fu
}

// SetAvailableSlots sets the "available_slots" field.
func (fu *FlightUpdate) SetAvailableSlots(i int) *FlightUpdate {
	fu.mutation.ResetAvailableSlots()
	fu.mutation.SetAvailableSlots(i)
	return fu
}

// AddAvailableSlots adds i to the "available_slots" field.
func (fu *FlightUpdate) AddAvailableSlots(i int) *FlightUpdate {
	fu.mutation.AddAvailableSlots(i)
	return fu
}

// SetFlightPlane sets the "flight_plane" field.
func (fu *FlightUpdate) SetFlightPlane(s string) *FlightUpdate {
	fu.mutation.SetFlightPlane(s)
	return fu
}

// SetCreatedAt sets the "created_at" field.
func (fu *FlightUpdate) SetCreatedAt(t time.Time) *FlightUpdate {
	fu.mutation.SetCreatedAt(t)
	return fu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fu *FlightUpdate) SetNillableCreatedAt(t *time.Time) *FlightUpdate {
	if t != nil {
		fu.SetCreatedAt(*t)
	}
	return fu
}

// SetUpdatedAt sets the "updated_at" field.
func (fu *FlightUpdate) SetUpdatedAt(t time.Time) *FlightUpdate {
	fu.mutation.SetUpdatedAt(t)
	return fu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (fu *FlightUpdate) SetNillableUpdatedAt(t *time.Time) *FlightUpdate {
	if t != nil {
		fu.SetUpdatedAt(*t)
	}
	return fu
}

// Mutation returns the FlightMutation object of the builder.
func (fu *FlightUpdate) Mutation() *FlightMutation {
	return fu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (fu *FlightUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, fu.sqlSave, fu.mutation, fu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fu *FlightUpdate) SaveX(ctx context.Context) int {
	affected, err := fu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fu *FlightUpdate) Exec(ctx context.Context) error {
	_, err := fu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fu *FlightUpdate) ExecX(ctx context.Context) {
	if err := fu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fu *FlightUpdate) check() error {
	if v, ok := fu.mutation.AvailableSlots(); ok {
		if err := flight.AvailableSlotsValidator(v); err != nil {
			return &ValidationError{Name: "available_slots", err: fmt.Errorf(`ent: validator failed for field "Flight.available_slots": %w`, err)}
		}
	}
	return nil
}

func (fu *FlightUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := fu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(flight.Table, flight.Columns, sqlgraph.NewFieldSpec(flight.FieldID, field.TypeInt))
	if ps := fu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fu.mutation.Name(); ok {
		_spec.SetField(flight.FieldName, field.TypeString, value)
	}
	if value, ok := fu.mutation.From(); ok {
		_spec.SetField(flight.FieldFrom, field.TypeString, value)
	}
	if value, ok := fu.mutation.To(); ok {
		_spec.SetField(flight.FieldTo, field.TypeString, value)
	}
	if value, ok := fu.mutation.DepartDate(); ok {
		_spec.SetField(flight.FieldDepartDate, field.TypeTime, value)
	}
	if value, ok := fu.mutation.DepartTime(); ok {
		_spec.SetField(flight.FieldDepartTime, field.TypeTime, value)
	}
	if value, ok := fu.mutation.ReturnDate(); ok {
		_spec.SetField(flight.FieldReturnDate, field.TypeTime, value)
	}
	if value, ok := fu.mutation.Status(); ok {
		_spec.SetField(flight.FieldStatus, field.TypeString, value)
	}
	if value, ok := fu.mutation.AvailableSlots(); ok {
		_spec.SetField(flight.FieldAvailableSlots, field.TypeInt, value)
	}
	if value, ok := fu.mutation.AddedAvailableSlots(); ok {
		_spec.AddField(flight.FieldAvailableSlots, field.TypeInt, value)
	}
	if value, ok := fu.mutation.FlightPlane(); ok {
		_spec.SetField(flight.FieldFlightPlane, field.TypeString, value)
	}
	if value, ok := fu.mutation.CreatedAt(); ok {
		_spec.SetField(flight.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := fu.mutation.UpdatedAt(); ok {
		_spec.SetField(flight.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flight.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	fu.mutation.done = true
	return n, nil
}

// FlightUpdateOne is the builder for updating a single Flight entity.
type FlightUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FlightMutation
}

// SetName sets the "name" field.
func (fuo *FlightUpdateOne) SetName(s string) *FlightUpdateOne {
	fuo.mutation.SetName(s)
	return fuo
}

// SetFrom sets the "from" field.
func (fuo *FlightUpdateOne) SetFrom(s string) *FlightUpdateOne {
	fuo.mutation.SetFrom(s)
	return fuo
}

// SetTo sets the "to" field.
func (fuo *FlightUpdateOne) SetTo(s string) *FlightUpdateOne {
	fuo.mutation.SetTo(s)
	return fuo
}

// SetDepartDate sets the "depart_date" field.
func (fuo *FlightUpdateOne) SetDepartDate(t time.Time) *FlightUpdateOne {
	fuo.mutation.SetDepartDate(t)
	return fuo
}

// SetDepartTime sets the "depart_time" field.
func (fuo *FlightUpdateOne) SetDepartTime(t time.Time) *FlightUpdateOne {
	fuo.mutation.SetDepartTime(t)
	return fuo
}

// SetReturnDate sets the "return_date" field.
func (fuo *FlightUpdateOne) SetReturnDate(t time.Time) *FlightUpdateOne {
	fuo.mutation.SetReturnDate(t)
	return fuo
}

// SetStatus sets the "status" field.
func (fuo *FlightUpdateOne) SetStatus(s string) *FlightUpdateOne {
	fuo.mutation.SetStatus(s)
	return fuo
}

// SetAvailableSlots sets the "available_slots" field.
func (fuo *FlightUpdateOne) SetAvailableSlots(i int) *FlightUpdateOne {
	fuo.mutation.ResetAvailableSlots()
	fuo.mutation.SetAvailableSlots(i)
	return fuo
}

// AddAvailableSlots adds i to the "available_slots" field.
func (fuo *FlightUpdateOne) AddAvailableSlots(i int) *FlightUpdateOne {
	fuo.mutation.AddAvailableSlots(i)
	return fuo
}

// SetFlightPlane sets the "flight_plane" field.
func (fuo *FlightUpdateOne) SetFlightPlane(s string) *FlightUpdateOne {
	fuo.mutation.SetFlightPlane(s)
	return fuo
}

// SetCreatedAt sets the "created_at" field.
func (fuo *FlightUpdateOne) SetCreatedAt(t time.Time) *FlightUpdateOne {
	fuo.mutation.SetCreatedAt(t)
	return fuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fuo *FlightUpdateOne) SetNillableCreatedAt(t *time.Time) *FlightUpdateOne {
	if t != nil {
		fuo.SetCreatedAt(*t)
	}
	return fuo
}

// SetUpdatedAt sets the "updated_at" field.
func (fuo *FlightUpdateOne) SetUpdatedAt(t time.Time) *FlightUpdateOne {
	fuo.mutation.SetUpdatedAt(t)
	return fuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (fuo *FlightUpdateOne) SetNillableUpdatedAt(t *time.Time) *FlightUpdateOne {
	if t != nil {
		fuo.SetUpdatedAt(*t)
	}
	return fuo
}

// Mutation returns the FlightMutation object of the builder.
func (fuo *FlightUpdateOne) Mutation() *FlightMutation {
	return fuo.mutation
}

// Where appends a list predicates to the FlightUpdate builder.
func (fuo *FlightUpdateOne) Where(ps ...predicate.Flight) *FlightUpdateOne {
	fuo.mutation.Where(ps...)
	return fuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (fuo *FlightUpdateOne) Select(field string, fields ...string) *FlightUpdateOne {
	fuo.fields = append([]string{field}, fields...)
	return fuo
}

// Save executes the query and returns the updated Flight entity.
func (fuo *FlightUpdateOne) Save(ctx context.Context) (*Flight, error) {
	return withHooks(ctx, fuo.sqlSave, fuo.mutation, fuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (fuo *FlightUpdateOne) SaveX(ctx context.Context) *Flight {
	node, err := fuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (fuo *FlightUpdateOne) Exec(ctx context.Context) error {
	_, err := fuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fuo *FlightUpdateOne) ExecX(ctx context.Context) {
	if err := fuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fuo *FlightUpdateOne) check() error {
	if v, ok := fuo.mutation.AvailableSlots(); ok {
		if err := flight.AvailableSlotsValidator(v); err != nil {
			return &ValidationError{Name: "available_slots", err: fmt.Errorf(`ent: validator failed for field "Flight.available_slots": %w`, err)}
		}
	}
	return nil
}

func (fuo *FlightUpdateOne) sqlSave(ctx context.Context) (_node *Flight, err error) {
	if err := fuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(flight.Table, flight.Columns, sqlgraph.NewFieldSpec(flight.FieldID, field.TypeInt))
	id, ok := fuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Flight.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := fuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, flight.FieldID)
		for _, f := range fields {
			if !flight.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != flight.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := fuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fuo.mutation.Name(); ok {
		_spec.SetField(flight.FieldName, field.TypeString, value)
	}
	if value, ok := fuo.mutation.From(); ok {
		_spec.SetField(flight.FieldFrom, field.TypeString, value)
	}
	if value, ok := fuo.mutation.To(); ok {
		_spec.SetField(flight.FieldTo, field.TypeString, value)
	}
	if value, ok := fuo.mutation.DepartDate(); ok {
		_spec.SetField(flight.FieldDepartDate, field.TypeTime, value)
	}
	if value, ok := fuo.mutation.DepartTime(); ok {
		_spec.SetField(flight.FieldDepartTime, field.TypeTime, value)
	}
	if value, ok := fuo.mutation.ReturnDate(); ok {
		_spec.SetField(flight.FieldReturnDate, field.TypeTime, value)
	}
	if value, ok := fuo.mutation.Status(); ok {
		_spec.SetField(flight.FieldStatus, field.TypeString, value)
	}
	if value, ok := fuo.mutation.AvailableSlots(); ok {
		_spec.SetField(flight.FieldAvailableSlots, field.TypeInt, value)
	}
	if value, ok := fuo.mutation.AddedAvailableSlots(); ok {
		_spec.AddField(flight.FieldAvailableSlots, field.TypeInt, value)
	}
	if value, ok := fuo.mutation.FlightPlane(); ok {
		_spec.SetField(flight.FieldFlightPlane, field.TypeString, value)
	}
	if value, ok := fuo.mutation.CreatedAt(); ok {
		_spec.SetField(flight.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := fuo.mutation.UpdatedAt(); ok {
		_spec.SetField(flight.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Flight{config: fuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, fuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{flight.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	fuo.mutation.done = true
	return _node, nil
}
