// Code generated by ent, DO NOT EDIT.

package ent

import (
	"booking/ent/booking"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BookingCreate is the builder for creating a Booking entity.
type BookingCreate struct {
	config
	mutation *BookingMutation
	hooks    []Hook
}

// SetBookingCode sets the "booking_code" field.
func (bc *BookingCreate) SetBookingCode(s string) *BookingCreate {
	bc.mutation.SetBookingCode(s)
	return bc
}

// SetBookingDate sets the "booking_date" field.
func (bc *BookingCreate) SetBookingDate(t time.Time) *BookingCreate {
	bc.mutation.SetBookingDate(t)
	return bc
}

// SetNillableBookingDate sets the "booking_date" field if the given value is not nil.
func (bc *BookingCreate) SetNillableBookingDate(t *time.Time) *BookingCreate {
	if t != nil {
		bc.SetBookingDate(*t)
	}
	return bc
}

// SetCancelDate sets the "cancel_date" field.
func (bc *BookingCreate) SetCancelDate(t time.Time) *BookingCreate {
	bc.mutation.SetCancelDate(t)
	return bc
}

// SetNillableCancelDate sets the "cancel_date" field if the given value is not nil.
func (bc *BookingCreate) SetNillableCancelDate(t *time.Time) *BookingCreate {
	if t != nil {
		bc.SetCancelDate(*t)
	}
	return bc
}

// SetCreatedAt sets the "created_at" field.
func (bc *BookingCreate) SetCreatedAt(t time.Time) *BookingCreate {
	bc.mutation.SetCreatedAt(t)
	return bc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bc *BookingCreate) SetNillableCreatedAt(t *time.Time) *BookingCreate {
	if t != nil {
		bc.SetCreatedAt(*t)
	}
	return bc
}

// SetUpdatedAt sets the "updated_at" field.
func (bc *BookingCreate) SetUpdatedAt(t time.Time) *BookingCreate {
	bc.mutation.SetUpdatedAt(t)
	return bc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (bc *BookingCreate) SetNillableUpdatedAt(t *time.Time) *BookingCreate {
	if t != nil {
		bc.SetUpdatedAt(*t)
	}
	return bc
}

// SetFlightID sets the "flight_id" field.
func (bc *BookingCreate) SetFlightID(i int) *BookingCreate {
	bc.mutation.SetFlightID(i)
	return bc
}

// SetCustomerID sets the "customer_id" field.
func (bc *BookingCreate) SetCustomerID(i int) *BookingCreate {
	bc.mutation.SetCustomerID(i)
	return bc
}

// SetNillableCustomerID sets the "customer_id" field if the given value is not nil.
func (bc *BookingCreate) SetNillableCustomerID(i *int) *BookingCreate {
	if i != nil {
		bc.SetCustomerID(*i)
	}
	return bc
}

// SetStatus sets the "status" field.
func (bc *BookingCreate) SetStatus(b booking.Status) *BookingCreate {
	bc.mutation.SetStatus(b)
	return bc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (bc *BookingCreate) SetNillableStatus(b *booking.Status) *BookingCreate {
	if b != nil {
		bc.SetStatus(*b)
	}
	return bc
}

// SetCustomerName sets the "customer_name" field.
func (bc *BookingCreate) SetCustomerName(s string) *BookingCreate {
	bc.mutation.SetCustomerName(s)
	return bc
}

// SetPhoneNumber sets the "phone_number" field.
func (bc *BookingCreate) SetPhoneNumber(s string) *BookingCreate {
	bc.mutation.SetPhoneNumber(s)
	return bc
}

// SetDob sets the "dob" field.
func (bc *BookingCreate) SetDob(s string) *BookingCreate {
	bc.mutation.SetDob(s)
	return bc
}

// SetEmail sets the "email" field.
func (bc *BookingCreate) SetEmail(s string) *BookingCreate {
	bc.mutation.SetEmail(s)
	return bc
}

// SetLicenseID sets the "license_id" field.
func (bc *BookingCreate) SetLicenseID(s string) *BookingCreate {
	bc.mutation.SetLicenseID(s)
	return bc
}

// SetAddress sets the "address" field.
func (bc *BookingCreate) SetAddress(s string) *BookingCreate {
	bc.mutation.SetAddress(s)
	return bc
}

// Mutation returns the BookingMutation object of the builder.
func (bc *BookingCreate) Mutation() *BookingMutation {
	return bc.mutation
}

// Save creates the Booking in the database.
func (bc *BookingCreate) Save(ctx context.Context) (*Booking, error) {
	bc.defaults()
	return withHooks(ctx, bc.sqlSave, bc.mutation, bc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BookingCreate) SaveX(ctx context.Context) *Booking {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BookingCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BookingCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BookingCreate) defaults() {
	if _, ok := bc.mutation.BookingDate(); !ok {
		v := booking.DefaultBookingDate
		bc.mutation.SetBookingDate(v)
	}
	if _, ok := bc.mutation.CreatedAt(); !ok {
		v := booking.DefaultCreatedAt
		bc.mutation.SetCreatedAt(v)
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		v := booking.DefaultUpdatedAt
		bc.mutation.SetUpdatedAt(v)
	}
	if _, ok := bc.mutation.Status(); !ok {
		v := booking.DefaultStatus
		bc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BookingCreate) check() error {
	if _, ok := bc.mutation.BookingCode(); !ok {
		return &ValidationError{Name: "booking_code", err: errors.New(`ent: missing required field "Booking.booking_code"`)}
	}
	if v, ok := bc.mutation.BookingCode(); ok {
		if err := booking.BookingCodeValidator(v); err != nil {
			return &ValidationError{Name: "booking_code", err: fmt.Errorf(`ent: validator failed for field "Booking.booking_code": %w`, err)}
		}
	}
	if _, ok := bc.mutation.BookingDate(); !ok {
		return &ValidationError{Name: "booking_date", err: errors.New(`ent: missing required field "Booking.booking_date"`)}
	}
	if _, ok := bc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Booking.created_at"`)}
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Booking.updated_at"`)}
	}
	if _, ok := bc.mutation.FlightID(); !ok {
		return &ValidationError{Name: "flight_id", err: errors.New(`ent: missing required field "Booking.flight_id"`)}
	}
	if v, ok := bc.mutation.FlightID(); ok {
		if err := booking.FlightIDValidator(v); err != nil {
			return &ValidationError{Name: "flight_id", err: fmt.Errorf(`ent: validator failed for field "Booking.flight_id": %w`, err)}
		}
	}
	if v, ok := bc.mutation.CustomerID(); ok {
		if err := booking.CustomerIDValidator(v); err != nil {
			return &ValidationError{Name: "customer_id", err: fmt.Errorf(`ent: validator failed for field "Booking.customer_id": %w`, err)}
		}
	}
	if _, ok := bc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Booking.status"`)}
	}
	if v, ok := bc.mutation.Status(); ok {
		if err := booking.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Booking.status": %w`, err)}
		}
	}
	if _, ok := bc.mutation.CustomerName(); !ok {
		return &ValidationError{Name: "customer_name", err: errors.New(`ent: missing required field "Booking.customer_name"`)}
	}
	if _, ok := bc.mutation.PhoneNumber(); !ok {
		return &ValidationError{Name: "phone_number", err: errors.New(`ent: missing required field "Booking.phone_number"`)}
	}
	if _, ok := bc.mutation.Dob(); !ok {
		return &ValidationError{Name: "dob", err: errors.New(`ent: missing required field "Booking.dob"`)}
	}
	if _, ok := bc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Booking.email"`)}
	}
	if _, ok := bc.mutation.LicenseID(); !ok {
		return &ValidationError{Name: "license_id", err: errors.New(`ent: missing required field "Booking.license_id"`)}
	}
	if v, ok := bc.mutation.LicenseID(); ok {
		if err := booking.LicenseIDValidator(v); err != nil {
			return &ValidationError{Name: "license_id", err: fmt.Errorf(`ent: validator failed for field "Booking.license_id": %w`, err)}
		}
	}
	if _, ok := bc.mutation.Address(); !ok {
		return &ValidationError{Name: "address", err: errors.New(`ent: missing required field "Booking.address"`)}
	}
	return nil
}

func (bc *BookingCreate) sqlSave(ctx context.Context) (*Booking, error) {
	if err := bc.check(); err != nil {
		return nil, err
	}
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	bc.mutation.id = &_node.ID
	bc.mutation.done = true
	return _node, nil
}

func (bc *BookingCreate) createSpec() (*Booking, *sqlgraph.CreateSpec) {
	var (
		_node = &Booking{config: bc.config}
		_spec = sqlgraph.NewCreateSpec(booking.Table, sqlgraph.NewFieldSpec(booking.FieldID, field.TypeInt))
	)
	if value, ok := bc.mutation.BookingCode(); ok {
		_spec.SetField(booking.FieldBookingCode, field.TypeString, value)
		_node.BookingCode = value
	}
	if value, ok := bc.mutation.BookingDate(); ok {
		_spec.SetField(booking.FieldBookingDate, field.TypeTime, value)
		_node.BookingDate = value
	}
	if value, ok := bc.mutation.CancelDate(); ok {
		_spec.SetField(booking.FieldCancelDate, field.TypeTime, value)
		_node.CancelDate = &value
	}
	if value, ok := bc.mutation.CreatedAt(); ok {
		_spec.SetField(booking.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := bc.mutation.UpdatedAt(); ok {
		_spec.SetField(booking.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := bc.mutation.FlightID(); ok {
		_spec.SetField(booking.FieldFlightID, field.TypeInt, value)
		_node.FlightID = value
	}
	if value, ok := bc.mutation.CustomerID(); ok {
		_spec.SetField(booking.FieldCustomerID, field.TypeInt, value)
		_node.CustomerID = &value
	}
	if value, ok := bc.mutation.Status(); ok {
		_spec.SetField(booking.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := bc.mutation.CustomerName(); ok {
		_spec.SetField(booking.FieldCustomerName, field.TypeString, value)
		_node.CustomerName = &value
	}
	if value, ok := bc.mutation.PhoneNumber(); ok {
		_spec.SetField(booking.FieldPhoneNumber, field.TypeString, value)
		_node.PhoneNumber = &value
	}
	if value, ok := bc.mutation.Dob(); ok {
		_spec.SetField(booking.FieldDob, field.TypeString, value)
		_node.Dob = &value
	}
	if value, ok := bc.mutation.Email(); ok {
		_spec.SetField(booking.FieldEmail, field.TypeString, value)
		_node.Email = &value
	}
	if value, ok := bc.mutation.LicenseID(); ok {
		_spec.SetField(booking.FieldLicenseID, field.TypeString, value)
		_node.LicenseID = &value
	}
	if value, ok := bc.mutation.Address(); ok {
		_spec.SetField(booking.FieldAddress, field.TypeString, value)
		_node.Address = &value
	}
	return _node, _spec
}

// BookingCreateBulk is the builder for creating many Booking entities in bulk.
type BookingCreateBulk struct {
	config
	builders []*BookingCreate
}

// Save creates the Booking entities in the database.
func (bcb *BookingCreateBulk) Save(ctx context.Context) ([]*Booking, error) {
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Booking, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BookingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BookingCreateBulk) SaveX(ctx context.Context) []*Booking {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BookingCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BookingCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
