// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Booking is the predicate function for booking builders.
type Booking func(*sql.Selector)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Flight is the predicate function for flight builders.
type Flight func(*sql.Selector)
